//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebManagementExcelDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agentii_Table
    {
        public string NrCrt { get; set; }
        public string Agentie { get; set; }
        public string Intrare { get; set; }
        public string Iesire { get; set; }
        public string Explicatii { get; set; }
        public string Operator { get; set; }
        public string DataOra { get; set; }
        public string Sold { get; set; }
        public string UltimaOp { get; set; }
        public string Zile { get; set; }
    }
}
