//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebManagementExcelDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Membrii
    {
        public string ID_Username { get; set; }
        public string Nume { get; set; }
        public string Prenume { get; set; }
        public string Email { get; set; }
        public string Parola { get; set; }
        public string ID_NumeFunctie { get; set; }
    
        public virtual Functie Functie { get; set; }
    }
}
